### ISSUE TITLE
FiberError: "fiber called across threads"

### ISSUE THREAD

**Issue by der-flo** [qades/sandboxed#1]
When using your gem in a webapp (Rails 3, Mongrel), calling something like `safe(:context => context) { eval str }` raises a FiberError with the message "fiber called across threads".
Are there solutions for this problem?

**Comment by qades** [comment]
I pushed a change that has been sitting on my drive for quite a while. It should also take care of the Fiber problem. If not, please reopen this bug.

**Comment by der-flo** [comment]
Thanks! I'll check it out soon.
